var pokeList = ['bulbasaur', 'ivysaur', 'venusaur', 'mega-venusaur', 'charmender', 'charmeleon', 'charizard', 'mega-charizard', 'squirtle', 'wartortle', 'blastoise', 'mega-blastoise', 'caterpie',
'metapod', 'butterfree', 'weedle', 'kakuna', 'beedrill', 'mega-beedrill', 'pidgey', 'pidgeotto', 'pidgeot', 'mega-pidgeot', 'rattata', 'raticate', 'spearow', 'fearow', 'ekans', 'arbok', 'pikachu',
'raichu', 'sandshrew', 'sandslash', 'nidoran', 'nidorina', 'nidorino', 'nidoqueen', 'nidoking', 'clefairy', 'clefable', 'vulpix', 'ninetales', 'jigglypuff', 'wigglytuff', 'zubat', 'golbat', 'oddish',
'gloom', 'vileplume', 'paras', 'parasect', 'venonat', 'venomoth', 'diglett', 'dugtrio', 'meowth', 'persian', 'psyduck', 'golduck', 'mankey', 'primeape', 'growlithe', 'arcanine', 'poliwag', 'poliwhirl',
'poliwrath', 'abra', 'kadabra', 'alakazam', 'mega-alakazam', 'machop', 'machoke', 'machamp', 'bellsprout', 'weepinbell', 'victreebel', 'tentacool', 'tentacruel', 'geodude', 'graveler', 'golem',
'ponyta', 'rapidash', 'slowpoke', 'slowbro', 'magnemite', 'magneton', 'farfetch\'d', 'doduo', 'dodrio', 'seel', 'dewgong', 'grimer', 'muk','shellder', 'cloyster', 'gastly', 'haunter', 'gengar',
'mega-gengar', 'onix', 'drowzee', 'hypno', 'krabby', 'kingler', 'voltorb', 'electrode', 'exeggcute', 'exeggutor', 'cubone', 'marowak', 'hitmonlee', 'hitmonchan', 'lickitung', 'koffing', 'weezing', 
'rhyhorn', 'rhydon', 'chansey', 'tangela', 'kangaskhan', 'mega-kangaskhan', 'horsea', 'seadra', 'goldeen', 'seaking', 'staryu', 'starmie', 'mr. mime', 'scyther', 'jynx', 'electabuzz', 'magmar',
'pinsir', 'mega-pinsir', 'tauros', 'magikarp', 'gyarados', 'mega-gyarados', 'lapras', 'ditto', 'eevee', 'vaporeon', 'jolteon', 'flareon', 'porygon', 'omanyte', 'omastar', 'kabuto', 'kabutops',
'aerodactyl', 'mega-aerodactyl', 'snorlax', 'articuno', 'moltres', 'zapdos', 'dratini', 'dragonair', 'dragonite', 'mew', 'mewtwo', /* GEN 1 */
'chikorita', 'bayleef', 'meganium', 'cyndaquil', 'quilava', 'typhlosion', 'totodile', 'croconaw', 'feraligatr', 'sentret', 'furret', 'hoothoot', 'noctowl', 'ledyba', 'ledian', 'spinarak',
'ariados', 'crobat', 'chinchou', 'lanturn', 'pichu', 'cleffa', 'igglybuff', 'togepi', 'togetic', 'natu', 'xatu', 'mareep', 'flaafy', 'ampharos', 'mega-ampharos', 'bellossom', 'marill', 'azumarill',
'sudowoodo', 'politoed', 'hoppip', 'skiploom', 'jumpluff', 'aipom', 'sunkern', 'sunflora', 'yanma', 'wooper', 'quagsire', 'espeon', 'umbreon', 'murkrow', 'slowking', 'misdreavus', 'unown', 'wobbuffet',
'girafarig', 'pineco', 'forretress', 'dunsparce', 'gligar', 'steelix', 'mega-steelix', 'snubbull', 'granbull', 'qwilfish', 'scizor', 'mega-scizor', 'shuckle', 'heracross', 'mega-heracross', 'sneasel',
'teddiursa', 'ursaring', 'slugma', 'magcargo', 'swinub', 'piloswine', 'corsola', 'remoraid', 'octillery', 'delibird', 'mantine', 'skarmory', 'houndour', 'houndoom', 'mega-houndoom', 'kingdra', 'phanpy',
'donphan', 'porygon2', 'stantler', 'smeargle', 'tyrogue', 'hitmontop', 'smoochum', 'elekid', 'magby', 'miltank', 'blissey', 'raikou', 'entei', 'suicune', 'larvitar', 'pupitar', 'tyranitar',
'mega-tyranitar', 'lugia', 'ho-oh', 'celebi', /* GEN 2 */
'treecko', 'grovyle', 'sceptile', 'mega-sceptile', 'torchic', 'combusken', 'blaziken', 'mega-blaziken', 'mudkip', 'marshtomp', 'swampert', 'mega-swampert', 'poochyena', 'mightyena', 'zigzagoon',
'linoone', 'wurmple', 'silcoon', 'beautifly', 'cascoon', 'dustox', 'lotad', 'lombre', 'ludicolo', 'seedot', 'nuzleaf', 'shiftry', 'tailow', 'swellow', 'wingull', 'pelipper', 'ralts', 'kirlia',
'gardevoir', 'mega-gardevoir', 'surskit', 'masquerain', 'shroomish', 'breloom', 'slakoth', 'vigoroth', 'slaking', 'nincada', 'ninjask', 'shedinja', 'whismur', 'loudred', 'exploud', 'makuhita',
'hariyama', 'azurill', 'nosepass', 'skitty', 'delcatty', 'sableye', 'mega-sableye', 'mawile', 'mega-mawile', 'aron', 'lairon', 'aggron', 'mega-aggron', 'meditite', 'medicham', 'mega-medicham',
'electrike', 'manectric', 'mega-manectric', 'plusle', 'minun', 'volbeat', 'illumise', 'roselia', 'gulpin', 'swallot', 'carvanha', 'sharpedo', 'mega-sharpedo', 'wailmer', 'wailord', 'numel', 'camerupt',
'mega-camerupt', 'torkoal', 'spoink', 'grumpig', 'spinda', 'trapinch', 'vibrava', 'flygon', 'cacnea', 'cacturn', 'swablu', 'altaria', 'mega-altaria', 'zangoose', 'seviper', 'lunatone', 'solrock',
'barboach', 'whiscash', 'corphish', 'crawdaunt', 'baltoy', 'claydol', 'lileep', 'cradily', 'anorith', 'armaldo', 'feebas', 'milotic', 'castform', 'kecleon', 'shuppet', 'banette', 'mega banette', 
'duskull', 'dusclops', 'tropius', 'chimecho', 'absol', 'mega-absol', 'wynaut', 'snorunt', 'glalie', 'mega-glalie', 'spheal', 'sealeo', 'walrein', 'clamperl', 'huntail', 'gorebyss', 'relicanth', 'luvdisc',
'bagon', 'shelgon', 'salamence', 'mega-salamence', 'beldum', 'metang', 'metagross', 'mega-metagross', 'regirock', 'regice', 'registeel', 'latias', 'mega-latias', 'latios', 'mega-latios', 'kyogre',
'primal-kyogre', 'groudon', 'primal-groudon', 'rayquaza', 'mega-rayquaza', 'jirachi', 'deoxys', /* GEN 3 */
'turtwig', 'grotle', 'torterra', 'chimchar', 'monferno', 'infernape', 'piplup', 'prinplup', 'empoleon', 'starly', 'staravia', 'staraptor', 'bidoof', 'bibarel', 'kricketot', 'kricketune', 'shinx',
'luxio', 'luxray', 'budew', 'roserade', 'cranidos', 'rampardos', 'shieldon', 'bastiodon', 'burmy', 'wormadam', 'mothim', 'combee', 'vespiqueen', 'pachirisu', 'buisel', 'floatzel', 'cherubi',
'cherrim', 'shellos', 'gastrodon', 'ambipom', 'drifloon', 'drifblim', 'buneary', 'lopunny', 'mega-lopunny', 'mismagius', 'honchkrow', 'glameow', 'purugly', 'chingling', 'stunky', 'skuntank', 'bronzor',
'bronzong', 'bonsly', 'mime jr', 'happiny', 'chatot', 'spiritomb', 'gible', 'gabite', 'garchomp', 'mega-garchomp', 'munchlax', 'riolu', 'lucario', 'mega-lucario', 'hippopotas', 'hippowdon', 'skorupi',
'drapion', 'croagunk', 'toxicroak', 'carnivine', 'finneon', 'lumineon', 'mantyke', 'snover', 'abomasnow', 'mega-abomasnow', 'weavile', 'magnezone', 'lickilicky', 'rhyperior', 'tangrowth', 'electivire',
'magmortar', 'togekiss', 'yanmega', 'leafeon', 'glaceon', 'gliscor', 'mamoswine', 'porygon-z', 'gallade', 'mega-gallade', 'probopass', 'dusknoir', 'froslass', 'rotom', 'rotom-wash', 'rotom-heat',
'rotom-fan', 'rotom-mow', 'rotom-frost', 'uxie', 'mesprit', 'azelf', 'dialga', 'palkia', 'heatran', 'regigigas', 'giratina-origin', 'giratina-altered', 'cresselia', 'phione', 'manaphy', 'darkrai',
'shaymin', 'shaymin-sky', 'arceus', /* GEN 4 */
'victini', 'snivy', 'servine', 'serperior', 'tepig', 'pignite', 'emboar', 'oshawott', 'dewott', 'samurott', 'patrat', 'watchog', 'lillipup', 'herdier', 'stoutland', 'purrloin', 'liepard', 'pansage',
'simisage', 'pansear', 'simisear', 'panpour', 'simipour', 'munna', 'musharna', 'pidove', 'tranquill', 'unfezant', 'blitzle', 'zebstrika', 'roggenrola', 'boldore', 'gigalith', 'woobat', 'swoobat',
'drilbur', 'excadrill', 'audino', 'mega-audino', 'timburr', 'gurdurr', 'conkeldurr', 'tympole', 'palpitoad', 'seismitoad', 'throh', 'sawk', 'sewaddle', 'swadloon', 'leavanny', 'venipede', 'whirlipede',
'scolipede', 'cottonee', 'whimsicott', 'petilil', 'liligant', 'basculin', 'sandile', 'krokorok', 'krookodile', 'darumaka', 'darmanitan', 'maractus', 'dwebble', 'crustle', 'scraggy', 'scrafty', 'sigilyph',
'yamask', 'cofagrigus', 'tirtouga', 'carracosta', 'archen', 'archeops', 'trubbish', 'garbodor', 'zorua', 'zoroark', 'minccino', 'cinccino', 'gothita', 'gothorita', 'gothitelle', 'solosis', 'dusosion',
'reuniclus', 'ducklett', 'swanna', 'vanillite', 'vanillish', 'vanilluxe', 'deerling', 'sawsbuck', 'emolga', 'karrablast', 'escavalier', 'foongus', 'amoonguss', 'frillish', 'jellicent', 'alomomola', 'joltik',
'galvantula', 'ferroseed', 'ferrothorn', 'klink', 'klang', 'klinklang', 'tynamo', 'elektrik', 'elektross', 'elgyem', 'beheeyem', 'litwick', 'lampent', 'chandelure', 'axew', 'fraxure', 'haxorus', 'cubchoo',
'beartic', 'cryogonal', 'shelmet', 'accelgor', 'stunfisk', 'mienfoo', 'mienshao', 'druddigon', 'golett', 'golurk', 'pawniard', 'bisharp', 'bouffalant', 'rufflet', 'braviary', 'vullaby', 'mandibuzz',
'heatmor', 'durant', 'deino', 'zweilous', 'hydreigon', 'larvesta', 'volcarona', 'cobalion', 'terrakion', 'virizion', 'tornadus', 'tornadus-therian', 'thundurus', 'thundurus-therian', 'landorus',
'landorus-therian', 'reshiram', 'zekrom', 'kyurem', 'kyurem-white', 'kyurem-black', 'keldeo', 'keldeo-resolute', 'meloetta', 'pirouette-meloetta', 'genesect', /* GEN 5 */
'chespin', 'quilladin', 'chesnaught', 'fennekin', 'braixen', 'delphox', 'froakie', 'frogadier', 'greninja', 'bunnelby', 'diggersby', 'fletchling', 'fletchinder', 'talonflame', 'scatterbug', 'spewpa',
'vivillon', 'litleo', 'pyroar', 'flabebe', 'floette', 'florges', 'skiddo', 'gogoat', 'pancham', 'pangoro', 'furfrou', 'espurr', 'meowstic', 'honedge', 'doublade', 'aegislash', 'spritzee', 'aromatisse',
'swirlix', 'slurpuff', 'inkay', 'malamar', 'binacle', 'barbaracle', 'skrelp', 'dragalge', 'clauncher', 'clawitzer', 'helioptile', 'heliolisk', 'tyrunt', 'tyrantrum', 'amaura', 'aurorus', 'sylveon',
'hawlucha', 'dedenne', 'carbink', 'goomy', 'sliggoo', 'goodra', 'klefki', 'phantump', 'trevenant', 'pumpkaboo', 'gourgeist', 'bergmite', 'avalugg', 'noibat', 'noivern', 'yveltal', 'zygarde', 'diancie',
'mega-diancie', 'hoopa', 'hoopa-unbound', 'volcanion' /* GEN 6 */];
